apiVersion: v1
kind: Secret
metadata:
  name: wrongsecrets-challenge62-secret
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "wrongsecrets-ctf-party.chart" . }}
type: Opaque
stringData:
  credentials: {{ .Values.balancer.challenge62GoogleCloudCredentials | default "" | quote }}
