apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrongsecrets-balancer
  labels:
    {{- include "wrongsecrets-ctf-party.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.balancer.replicas }}
  selector:
    matchLabels:
      {{- include "wrongsecrets-ctf-party.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/wrongsecrets-balancer/config-map.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/wrongsecrets-balancer/secret.yaml") . | sha256sum }}
      labels:
        {{- include "wrongsecrets-ctf-party.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      serviceAccountName: wrongsecrets-balancer
      {{- with .Values.balancer.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: '{{ .Values.balancer.repository }}:{{ .Values.balancer.tag | default (printf "v%s" .Chart.Version) }}'
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /balancer/
              port: http
          readinessProbe:
            httpGet:
              path: /balancer/
              port: http
          env:
            - name: REACT_APP_MOVING_GIF_LOGO
              value: {{ .Values.balancer.env.REACT_APP_MOVING_GIF_LOGO }}
            - name: REACT_APP_ACCESS_PASSWORD
              value: {{ .Values.balancer.env.REACT_APP_ACCESS_PASSWORD }}
            - name: REACT_APP_HEROKU_WRONGSECRETS_URL
              value: {{ .Values.balancer.env.REACT_APP_HEROKU_WRONGSECRETS_URL }}
            - name: REACT_APP_CTFD_URL
              value: {{ .Values.balancer.env.REACT_APP_CTFD_URL }}
            - name: REACT_APP_S3_BUCKET_URL
              value: {{ .Values.balancer.env.REACT_APP_S3_BUCKET_URL }}
            - name: K8S_ENV
              value: {{ .Values.balancer.env.K8S_ENV }}
            - name: IRSA_ROLE
              value: "arn:aws:iam::233483431651:role/wrongsecrets-secret-manager" #REPLACE WITH THE ACTUAL AWS ROLE IF IN AWS MODE
            - name: COOKIEPARSER_SECRET
              valueFrom:
                secretKeyRef:
                  name: wrongsecrets-balancer-secret
                  key: cookieParserSecret
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wrongsecrets-balancer-secret
                  key: adminPassword
            {{- if .Values.balancer.metrics.enabled }}
            - name: METRICS_BASICAUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wrongsecrets-balancer-secret
                  key: metricsBasicAuthUsername
            - name: METRICS_BASICAUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wrongsecrets-balancer-secret
                  key: metricsBasicAuthPassword
            {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          volumeMounts:
            - name: config-volume
              mountPath: /home/app/config/
          resources:
            {{- toYaml .Values.balancer.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: wrongsecrets-balancer-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.balancer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.balancer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
