{{- if and .Values.balancer.metrics.enabled .Values.balancer.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wrongsecrets-balancer
spec:
  selector:
    matchLabels:
      {{- include "wrongsecrets-ctf-party.labels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.service.portName }}
      path: {{ .Values.balancer.metrics.serviceMonitor.path | quote }}
      basicAuth:
        username:
          name: wrongsecrets-balancer-secret
          key: metricsBasicAuthUsername
        password:
          name: wrongsecrets-balancer-secret
          key: metricsBasicAuthPassword
{{- end }}
