{{- if and .Values.balancer.metrics.enabled .Values.balancer.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wrongsecrets-metrics
spec:
  targetLabels:
    - team
  selector:
    matchLabels:
      app: wrongsecrets
      deployment-context: {{ .Release.Name | quote }}
  endpoints:
    - targetPort: {{ .Values.balancer.metrics.serviceMonitor.targetPort }}
{{- end }}
