---
# Source: wrongsecrets-ctf-party/templates/cleanup/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wrongsecrets-cleaner
  labels:
    helm.sh/chart: wrongsecrets-ctf-party-0.1.0-alpha
---
# Source: wrongsecrets-ctf-party/templates/wrongsecrets-balancer/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wrongsecrets-balancer
  labels:
    helm.sh/chart: wrongsecrets-ctf-party-0.1.0-alpha
---
# Source: wrongsecrets-ctf-party/templates/wrongsecrets-balancer/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: wrongsecrets-balancer-secret
  labels:
    app.kubernetes.io/instance: myrelease
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: wrongsecrets-ctf-party-0.1.0-alpha
type: Opaque
data:
  cookieParserSecret: "RlN2YWpQdlRsRHhLcTBGS0JGekxWZ2F4"
  adminPassword: "UloxQVlTTEY="
  metricsBasicAuthUsername: "cHJvbWV0aGV1cy1zY3JhcGVy"
  metricsBasicAuthPassword: "RVJ6Q1Q0cHdCRHhmQ0tSR21mck1hOEtROHNYZjhHS3k="
---
# Source: wrongsecrets-ctf-party/templates/wrongsecrets-balancer/config-map.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: wrongsecrets-balancer-config
  labels:
    helm.sh/chart: wrongsecrets-ctf-party-0.1.0-alpha
data:
  config.json: |
    {
      "port": 3000,
      "namespace": "myns",
      "deploymentContext": "myrelease",
      "maxJuiceShopInstances": 500,
      "skipOwnerReference": false,
      "cookieParser": {
        "cookieName": "balancer",
        "secure": false
      },
      "admin": {
        "username": "admin"
      },
      "metrics": {
        "enabled": true
      },
      "wrongsecrets": {
        "image": "jeroenwillemsen/wrongsecrets",
        "tag": "1.6.5-no-vault",
        "imagePullPolicy": "IfNotPresent",
        "ctfKey": "zLp@.-6fMW6L-7R3b!9uR_K!NfkkTr",
        "nodeEnv": "wrongsecrets-ctf-party",
        "resources": {"requests":{"cpu":"256Mi","memory":"300Mi"}},
        "securityContext": {"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"readOnlyRootFilesystem":true,"runAsNonRoot":true,"seccompProfile":{"type":"RuntimeDefault"}},
        "env": [{"name":"K8S_ENV","value":"k8s"},{"name":"SPECIAL_K8S_SECRET","valueFrom":{"configMapKeyRef":{"key":"funny.entry","name":"secrets-file"}}},{"name":"SPECIAL_SPECIAL_K8S_SECRET","valueFrom":{"secretKeyRef":{"key":"funnier","name":"funnystuff"}}}],
        "envFrom": [],
        "volumes": [],
        "volumeMounts": null,
        "affinity": {},
        "tolerations": [],
        "runtimeClassName": null
      }
    }
---
# Source: wrongsecrets-ctf-party/templates/wrongsecrets/config-map.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: wrongsecrets-config
  labels:
    helm.sh/chart: wrongsecrets-ctf-party-0.1.0-alpha
data:
  wrongsecrets-ctf-party.yaml: |-
    K8S_ENV: aws
---
# Source: wrongsecrets-ctf-party/templates/cleanup/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # namespace: "myns"
  name: wrongsecrets-cleaner
  labels:
    helm.sh/chart: wrongsecrets-ctf-party-0.1.0-alpha
rules:
  - apiGroups: ['apps']
    resources: ['deployments']
    verbs: ['get', 'delete', 'list']
  - apiGroups: [''] # "" indicates the core API group
    resources: ['services']
    verbs: ['get', 'delete']
  - apiGroups: [''] # "" indicates the core API group
    resources: ['namespaces']
    verbs: ['get', 'delete', 'list']
---
# Source: wrongsecrets-ctf-party/templates/wrongsecrets-balancer/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wrongsecrets-balancer
  labels:
    helm.sh/chart: wrongsecrets-ctf-party-0.1.0-alpha
rules:
  - apiGroups: ['apps']
    resources: ['deployment', 'deployments']
    verbs: ['get', 'create', 'list', 'delete', 'patch', 'watch', 'update']
  - apiGroups: [''] # "" indicates the core API group
    resources: ['services']
    verbs: ['get', 'list', 'create', 'delete']
  - apiGroups: [''] # "" indicates the core API group
    resources: ['pod', 'pods', 'pods/log']
    verbs: ['create', 'get', 'list', 'delete', 'watch']
  - apiGroups: [''] # "" indicates the core API group
    resources: ['namespaces']
    verbs: ['get', 'create', 'list', 'delete', 'patch', 'watch', 'update']
  - apiGroups: [''] # "" indicates the core API group
    resources: ['configmaps']
    verbs: ['create', 'get', 'list', 'delete']
  - apiGroups: [''] # "" indicates the core API group
    resources: ['secrets']
    verbs: ['create', 'get', 'list', 'delete']
  - apiGroups: ['']
    resources: ['serviceaccounts']
    verbs: ['create', 'get', 'list', 'delete', 'patch', 'update']
  - apiGroups: ['rbac.authorization.k8s.io']
    resources: ['roles']
    verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch', 'admin', 'escalate']
  - apiGroups: ['rbac.authorization.k8s.io']
    resources: ['rolebindings']
    verbs: ['create', 'get', 'list', 'delete', 'patch', 'grant', 'bind', 'escalate']
  - apiGroups: ['rbac.authorization.k8s.io']
    resources: ['roleRef']
    verbs: ['create', 'get', 'list', 'delete', 'patch', 'grant', 'escalate']
  - apiGroups: ['secrets-store.csi.x-k8s.io']
    resources: ['secretproviderclasses']
    verbs: ['create', 'get', 'list', 'delete']
  - apiGroups: ['networking.k8s.io']
    resources: ['networkpolicies']
    verbs: ['create', 'get', 'list', 'delete']
  - apiGroups: ['']
    resources: ['endpoints']
    verbs: [ 'get', 'list']
---
# Source: wrongsecrets-ctf-party/templates/cleanup/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wrongsecrets-cleaner
  # namespace: "myns"
  labels:
    helm.sh/chart: wrongsecrets-ctf-party-0.1.0-alpha
subjects:
  - kind: ServiceAccount
    name: wrongsecrets-cleaner # Name is case sensitive
    namespace: "myns"
roleRef:
  kind: ClusterRole
  name: wrongsecrets-cleaner
  apiGroup: rbac.authorization.k8s.io
---
# Source: wrongsecrets-ctf-party/templates/wrongsecrets-balancer/role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wrongsecrets-balancer
  labels:
    helm.sh/chart: wrongsecrets-ctf-party-0.1.0-alpha
subjects:
  - kind: ServiceAccount
    name: wrongsecrets-balancer # Name is case sensitive
    namespace: "myns"
roleRef:
  kind: ClusterRole
  name: wrongsecrets-balancer
  apiGroup: rbac.authorization.k8s.io
---
# Source: wrongsecrets-ctf-party/templates/wrongsecrets-balancer/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: wrongsecrets-balancer
  labels:
    helm.sh/chart: wrongsecrets-ctf-party-0.1.0-alpha
    app.kubernetes.io/name: wrongsecrets-ctf-party
    app.kubernetes.io/instance: myrelease
    app.kubernetes.io/version: "1.5.9"
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: myrelease
    meta.helm.sh/release-namespace: myns
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: wrongsecrets-ctf-party
    app.kubernetes.io/instance: myrelease
  ports:
    - port: 3000
      name: web
---
# Source: wrongsecrets-ctf-party/templates/wrongsecrets-balancer/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrongsecrets-balancer
  labels:
    app: wrongsecrets-balancer
    helm.sh/chart: wrongsecrets-ctf-party-0.1.0-alpha
    app.kubernetes.io/name: wrongsecrets-ctf-party
    app.kubernetes.io/instance: myrelease
    app.kubernetes.io/version: "1.5.9"
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: myrelease
    meta.helm.sh/release-namespace: myns
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: wrongsecrets-ctf-party
      app.kubernetes.io/instance: myrelease
  template:
    metadata:
      annotations:
        checksum/config: f3575d7162cebea5a4ee8a5d79c3bbaa9bcc52999b00d5c4a992c13227ee47d4
        checksum/secret: 35af980afb984cfccbedfb4e89b525a14a7bb962910f19ab33e51a24b18bf1c3
      labels:
        app: wrongsecrets-balancer
        app.kubernetes.io/name: wrongsecrets-ctf-party
        app.kubernetes.io/instance: myrelease
    spec:
      serviceAccountName: wrongsecrets-balancer
      securityContext:
        fsGroup: 2000
        runAsGroup: 3000
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: wrongsecrets-ctf-party
          image: 'jeroenwillemsen/wrongsecrets-balancer:1.6.5aws'
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /balancer/
              port: http
          readinessProbe:
            httpGet:
              path: /balancer/
              port: http
          env:
            - name: CHALLENGE33_VALUE
              value: "VkJVR2gzd3UvM0kxbmFIajFVZjk3WTBMcThCNS85MnExandwMy9hWVN3SFNKSThXcWRabllMajc4aEVTbGZQUEtmMVpLUGFwNHoyK3IrRzlOUndkRlUvWUJNVFkzY05ndU1tNUM2bDJwVEs5SmhQRm5VemVySXdNcm5odTlHanJxU0ZuL0J0T3ZMblFhL21TZ1hETkpZVU9VOGdDSEZzOUpFZVF2OWhwV3B5eGxCMk5xdTBNSHJQTk9EWTNab2hoa2pXWGF4YmpDWmk5U3BtSHlkVTA2WjdMcVd5RjM5RzZWOENGNkxCUGtkVW4zYUpBVisrRjBROUljU009Cg=="
            - name: IRSA_ROLE
              value: "arn:aws:iam::233483431651:role/wrongsecrets-secret-manager"
            - name: K8S_ENV
              value: "k8s"
            - name: REACT_APP_ACCESS_PASSWORD
              value: ""
            - name: REACT_APP_CREATE_TEAM_HMAC_KEY
              value: "hardcodedkey"
            - name: REACT_APP_CTFD_URL
              value: "https://ctfd.io"
            - name: REACT_APP_HEROKU_WRONGSECRETS_URL
              value: "https://wrongsecrets-ctf.herokuapp.com"
            - name: REACT_APP_MOVING_GIF_LOGO
              value: "https://i.gifer.com/9kGQ.gif"
            - name: REACT_APP_S3_BUCKET_URL
              value: "s3://funstuff"
            - name: SECRETS_MANAGER_SECRET_ID_1
              value: "wrongsecret"
            - name: SECRETS_MANAGER_SECRET_ID_2
              value: "wrongsecret-2"
            - name: WRONGSECRETS_TAG
              value: 1.6.5-no-vault
            - name: WRONGSECRETS_DESKTOP_TAG
              value: 1.6.5
            - name: COOKIEPARSER_SECRET
              valueFrom:
                secretKeyRef:
                  name: wrongsecrets-balancer-secret
                  key: cookieParserSecret
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wrongsecrets-balancer-secret
                  key: adminPassword
            - name: METRICS_BASICAUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wrongsecrets-balancer-secret
                  key: metricsBasicAuthUsername
            - name: METRICS_BASICAUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wrongsecrets-balancer-secret
                  key: metricsBasicAuthPassword
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
              - CAP_NET_ADMIN
              - CAP_NET_BIND_SERVICE
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /home/app/config/
              name: config-volume
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 400m
              memory: 256Mi
      volumes:
        - configMap:
            name: wrongsecrets-balancer-config
          name: config-volume
---
# Source: wrongsecrets-ctf-party/templates/cleanup/cron-job.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: 'cleanup-job'
spec:
  schedule: "0,15,30,45 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            name: 'cleanup-job'
            helm.sh/chart: wrongsecrets-ctf-party-0.1.0-alpha
        spec:
          serviceAccountName: 'wrongsecrets-cleaner'
          securityContext:
            fsGroup: 2000
            runAsGroup: 3000
            runAsUser: 1000
          containers:
            - image: 'jeroenwillemsen/wrongsecrets-ctf-cleaner:0.4'
              imagePullPolicy: "IfNotPresent"
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - ALL
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              name: 'cleanup-job'
              env:
                - name: MAX_INACTIVE_DURATION
                  value: "2d"
                - name: SHOULD_DELETE
                  value: "false"
                - name: NAMESPACE
                  value: "myns"
          restartPolicy: Never
