on: [push, pull_request]
permissions:
  contents: read
name: "Run Tests"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  cleaner:
    name: Cleaner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 26
          cache: npm
          cache-dependency-path: |
            cleaner/package-lock.json
      - name: Install Balancer
        run: |
          cd cleaner
          npm ci
      - name: Run Linter
        run: |
          cd cleaner
          npm run lint
      - name: Test Balancer
        run: |
          cd cleaner
          npm test -- --ci --color --verbose
  balancer:
    name: Balancer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 26
          cache: npm
          cache-dependency-path: |
            wrongsecrets-balancer/package-lock.json
            wrongsecrets-balancer/ui/package-lock.json
      - name: "Install & Build BalancerUI"
        run: |
          cd wrongsecrets-balancer/ui
          npm ci --legacy-peer-deps
          npm run build
      - name: Install Balancer
        run: |
          cd wrongsecrets-balancer
          npm ci
      - name: Run Linter
        run: |
          cd wrongsecrets-balancer
          npm run lint
      - name: Test Balancer
        run: |
          cd wrongsecrets-balancer
          npm test -- --ci --color --verbose
